Making branch compatible with Vivado 2023.1. Big changes are inclusio…
casper-astro/mlib_devel pull request #211
Opened 2024-08-08 18:04 UTC by bgodfrey

…n of -E flag to keep Vivado from changing Python path variables in jasper_frontend.m and toolflow.py, updating red_pitaya and microblaze .tcl files to be compatible with 2023.1, and some small python fixes in xml2vhdl. All tutorials for RFDC, Red Pitaya, and SNAP boards have been tested and most have been tested on hardware

2024-08-09 16:15 UTC, jkocz commented
There are some local files that got accidentally added to the repo. These will be removed, and an extra test run on the SNAP microblaze update to make sure there were no complications.

2024-08-09 16:16 UTC, mitchburnett requested changes
Can you please remove a lot of the locally tracked files, and then resubmit (e.g., .Xil folder, log files, .htm files)

2024-08-20 17:37 UTC, jkocz approved these changes
Thanks @bgodfrey - though I'll go in and remove the extra line from .gitignore once it's merged, just to try and keep that non-specific to any repo.

2024-08-20 17:37 UTC, jkocz approved these changes

2024-08-20 17:37 UTC, merged